# Generated by Django 4.2.30 on 2026-10-08 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения актуальности'),
        ),
        migrations.AddField(
            model_name='article',
            name='last_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_articles', to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил актуальность'),
        ),
        migrations.AddField(
            model_name='article',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_articles', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за содержание'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Разрешено'),
        ),
        migrations.AddField(
            model_name='comment',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RelatedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('bt_tz', 'БТ/ТЗ'), ('youtrack', 'Задача YouTrack'), ('git', 'Git'), ('docs', 'Документация'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип связи')),
                ('url', models.URLField(max_length=1000, verbose_name='Ссылка')),
                ('label', models.CharField(blank=True, help_text='Например: БТ по доработке X, задача на реализацию Y', max_length=300, verbose_name='Назначение связи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='knowledge.article')),
            ],
            options={
                'verbose_name': 'Связанный источник',
                'verbose_name_plural': 'Связанные источники',
                'ordering': ['link_type', 'created_at'],
            },
        ),
    ]
