# Generated by Django 4.2.30 on 2026-10-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_article_last_verified_at_article_last_verified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedlink',
            name='link_type',
            field=models.CharField(choices=[('bt', 'БТ'), ('tz', 'ТЗ'), ('youtrack', 'Задача YouTrack'), ('git', 'Git'), ('docs', 'Документация'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип связи'),
        ),
    ]
