# Generated by Django 4.2.30 on 2026-10-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_relatedlink_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sticker',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='comment',
            name='text_html',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='comments/%Y/%m/')),
                ('name', models.CharField(max_length=255)),
                ('is_image', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='knowledge.comment')),
            ],
        ),
    ]
